import { NextResponse } from 'next/server'
import { errorResponse, syncResult } from '@/lib/http'
import { getFileContent, getDirectory, updateFile, commitAndPush } from '@/lib/github'
import { parseConfig, updateSkillInConfig } from '@/lib/config'
import type { Pack, PackSkill, CommunityPack } from '@/lib/types'

// Shape of packs.json (generated by ./generate-packs-json from packs.config.json
// + skills.json). Membership only — live enabled/installed state is joined here.
interface PacksManifest {
  packs?: Array<{
    key: string
    name: string
    description: string
    color: string
    category: string | null
    default_enabled?: string[]
    skills?: Array<{ slug: string; name: string; description: string; category: string }>
  }>
}

interface CommunityManifest {
  packs?: Array<Omit<CommunityPack, 'installedCount'>>
}

/**
 * GET /api/packs — the first-party pack catalog (packs.json) joined with live
 * enabled state from aeon.yml, plus the community registry (skill-packs.json)
 * joined with on-disk installed state. Both manifests are optional; a missing
 * file yields an empty list rather than a 500.
 */
export async function GET() {
  try {
    const config = await getFileContent('aeon.yml')
      .then(r => parseConfig(r.content))
      .catch(() => null)
    const enabledOf = (slug: string) => config?.skills[slug]?.enabled ?? false

    // First-party packs
    let firstParty: Pack[] = []
    try {
      const { content } = await getFileContent('packs.json')
      const manifest = JSON.parse(content) as PacksManifest
      firstParty = (manifest.packs ?? []).map(p => {
        const skills: PackSkill[] = (p.skills ?? []).map(s => ({
          slug: s.slug,
          name: s.name,
          description: s.description,
          category: s.category,
          enabled: enabledOf(s.slug),
        }))
        return {
          key: p.key,
          name: p.name,
          description: p.description,
          color: p.color,
          category: p.category,
          default_enabled: p.default_enabled ?? [],
          skills,
          total: skills.length,
          enabled: skills.filter(s => s.enabled).length,
        }
      })
    } catch { /* packs.json optional */ }

    // Community packs — count how many of each pack's skills exist on disk.
    let community: CommunityPack[] = []
    try {
      const { content } = await getFileContent('skill-packs.json')
      const manifest = JSON.parse(content) as CommunityManifest
      const installed = new Set(
        (await getDirectory('skills')).filter(d => d.type === 'dir').map(d => d.name),
      )
      community = (manifest.packs ?? []).map(p => ({
        ...p,
        installedCount: (p.skills ?? []).filter(s => installed.has(s)).length,
      }))
    } catch { /* skill-packs.json optional */ }

    return NextResponse.json({ firstParty, community })
  } catch (error: unknown) {
    return errorResponse(error, 'Unknown error')
  }
}

/**
 * PATCH /api/packs — bulk enable/disable every skill in a first-party pack.
 * Body: { pack: string, enabled: boolean }. Resolves the pack's member slugs
 * from packs.json, flips each skill's `enabled` in aeon.yml, and writes once.
 * Skills with no aeon.yml entry are reported in `skipped` rather than failing.
 */
export async function PATCH(request: Request) {
  try {
    const { pack, enabled } = await request.json() as { pack?: string; enabled?: boolean }
    if (!pack || typeof enabled !== 'boolean') {
      return NextResponse.json({ error: 'pack (string) and enabled (boolean) are required' }, { status: 400 })
    }

    const { content: manifestRaw } = await getFileContent('packs.json')
    const manifest = JSON.parse(manifestRaw) as PacksManifest
    const target = (manifest.packs ?? []).find(p => p.key === pack)
    if (!target) {
      return NextResponse.json({ error: `Unknown pack: ${pack}` }, { status: 404 })
    }
    const slugs = (target.skills ?? []).map(s => s.slug)

    const { content, sha } = await getFileContent('aeon.yml')
    const cfg = parseConfig(content)
    let updated = content
    const changed: string[] = []
    const skipped: string[] = []
    for (const slug of slugs) {
      if (!(slug in cfg.skills)) { skipped.push(slug); continue }
      if (cfg.skills[slug].enabled === enabled) continue // already in target state
      updated = updateSkillInConfig(updated, slug, { enabled })
      changed.push(slug)
    }

    let sync: { synced: boolean; reason?: string } = { synced: true }
    if (updated !== content) {
      const msg = `chore: ${enabled ? 'enable' : 'disable'} ${pack} pack (${changed.length} skill${changed.length === 1 ? '' : 's'})`
      await updateFile('aeon.yml', updated, sha, msg)
      sync = commitAndPush(['aeon.yml'], msg)
    }

    return NextResponse.json({ ...syncResult(sync), changed, skipped })
  } catch (error: unknown) {
    return errorResponse(error, 'Unknown error')
  }
}
